### PR TITLE
Retrieve agent information from Gatekeeper

### PR DESCRIPTION
**Pull request by khyberspache**
* Hits the agent endpoint to get agent information
* Downloads are proxied through gatekeeper so users can download licensed content

### CODE REVIEW

**Review by privateducky — APPROVED** [review]
Code looks good. Pending testing, this can be merged with the 0.9.10 version release (as it uses REST endpoints that are not yet available)

**Review by privateducky — CHANGES_REQUESTED** [review]
From testing:
- ThirdEye is no longer in the list
- Can you rename 'code' to 'source code'?

**Comment by privateducky** [comment]
@khyberspache per my comment about ThirdEye not showing up in the list. Let's add ThirdEye to the agents.yml and strip out the code block that dynamically adds it inside Operator. Consistency is king (I should have written it that way to begin with).

**Comment by privateducky** [comment]
@khyberspache one last change: can you add a 1-line description to each agent in agents.yml and render it here where the 'download by clicking..' line is? you can move that instruction to the 'select an agent' header box above.

**Comment by khyberspache** [comment]
The agent code is already out of operator - so that part is done. The rest is easy, I'll get the rest in tonight

**Comment by khyberspache** [comment]
All comments addressed. Requires latest gatekeeper updates for agent info.

**Pull request merged**
