### PR TITLE
Adding adversary generation via Navigator layer

### PR DESCRIPTION
**Pull request by bfuzzy1**
@lzimm needs your design magic on this. 🤣

### CODE REVIEW

**Comment by lzimm** [comment]
@bfuzzy1 wanna give those changes a try? :)

**Comment by bfuzzy1** [comment]
@lzimm dude you rock! I appreciate the help on this!

**Comment by bfuzzy1** [comment]
My bad guys borking a separate PR

**Comment by privateducky** [comment]
@bfuzzy1 i'm circling back to this PR, which looks like it needs a rebase (unsure of what are the intended changes and not). Can you rebase and I can re-look at?

**Comment by bfuzzy1** [comment]
@privateducky I'm going to close this and re-submit something more clean. Made a mess of this one.

**Pull request closed without merging**
