### PR TITLE
ChangeTheme plugin (LightMode replacement)

### PR DESCRIPTION
**Pull request by bfuzzy1**
Adding a replacement of the lightmode plugin that adds 2 buttons to allow users to toggle between light and dark mode themes.

Should take care of issue #80

### CODE REVIEW

**Comment by bfuzzy1** [comment]
PR also removes lightmode plugin 👍

**Comment by khyberspache** [comment]
This was literally in our backlog... you are a wizard

**Review by khyberspache — APPROVED** [review]
Tested, works nicely

**Review by privateducky — APPROVED** [review]

**Comment by bfuzzy1** [comment]
:D Thanks @privateducky!

**Pull request merged**
